### PR TITLE
Yesterday is t-1 not t

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Review by melofton — APPROVED** [review]
thank you so much for catching this @ethanwhite ! 🙌

**Comment by melofton** [comment]
@ethanwhite I've just re-published this module to shinyapps.io with your correction - thank you again!

**Comment by ethanwhite** [comment]
You're welcome! It's a really cool module. We're considering integrating it into our material on uncertainty next year https://github.com/weecology/forecasting-course/issues/81

**Comment by melofton** [comment]
Oh, nice! If you do and it's helpful to talk through anything, just reach out! And we are always open to feedback on how to improve. Cheers!

**Pull request merged**
